### PR TITLE
Fix compiler error: may be used uninitialized in this function [-Werr…

### PR DESCRIPTION
**Pull request by tuxmaster5000**
Fix for https://github.com/greenbone/gvm-libs/issues/397

### CODE REVIEW

**Review by mattmundell — CHANGES_REQUESTED** [review]
Also for this one.  Can you make it against gvm-libs-20.08?  Otherwise it will only be released in 21.04.

**Comment by tuxmaster5000** [comment]
> Also for this one. Can you make it against gvm-libs-20.08? Otherwise it will only be released in 21.04.

When I simple change the target branch then it will fail's because many other files will changed. :(

**Comment by mattmundell** [comment]
> When I simple change the target branch then it will fail's because many other files will changed. :(

Yes, I had the same problem on https://github.com/greenbone/gvmd/pull/1280.

I"m not sure how the OP handled it.  I guess by using a `git rebase` command on their local tree.

**Comment by bjoernricks** [comment]
`git --onto` is your fried. See https://medium.com/@gabriellamedas/git-rebase-and-git-rebase-onto-a6a3f83f9cce for some details.

**Comment by ArnoStiefvater** [comment]
Thank you for contributing! It appears this fix was already applied to a different branch with https://github.com/greenbone/gvm-libs/pull/448 and merged some time later into 21.04 and master, therefore closing the PR.

**Pull request closed without merging**
